name = "speculoosje"
main = "worker/index.js"
compatibility_date = "2026-07-01"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "LOOS_KV"
id = "8aa3e6d65da3418c859228888f255392"